import { CRYPTO_CURRENCY_MAP, SYNTHS_MAP } from '../../constants/currency';

export const COLLATERAL_PAIR = {
	LOCKED_CURRENCY_KEY: CRYPTO_CURRENCY_MAP.ETH,
	BORROWED_CURRENCY_KEY: SYNTHS_MAP.sETH,
	MIN_LOAN_SIZE: 1,
	ISSUANCE_RATIO: 1.5,
	COLLAT_RATIO_PERCENT: 750 / 100,
	INTEREST_RATE_PERCENT: 5 / 100,
	MINTING_FEE_PERCENT: 0.05 / 100,
};
