env_defaults: &env_defaults
  working_directory: ~
  docker:
    - image: circleci/node:10.16

version: 2.1
jobs:
  build:
    <<: *env_defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1.0-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1.0-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1.0-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run lint

  test:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm test

workflows:
  version: 2

  build-lint-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
