export const ethersCollateralsUSD = {
	addresses: {
		1: '0x0D69755e12107695E544842BF7F61D9193f09a54',
		3: '0x26a3C1878c4f3598e58f8bFB60B3cD9EF083e892',
		4: '0xba6c0220157008cecb7364b37e27885e7b5be74a',
		42: '0x83908C2ce5cD86C2924f69C4C8B17dCFB789C026',
	},
	abi: [
		{
			inputs: [
				{ internalType: 'address', name: '_owner', type: 'address' },
				{ internalType: 'address', name: '_resolver', type: 'address' },
			],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'constructor',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, internalType: 'uint256', name: 'loanLimit', type: 'uint256' }],
			name: 'AccountLoanLimitUpdated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'address', name: 'account', type: 'address' },
				{ indexed: false, internalType: 'uint256', name: 'loanID', type: 'uint256' },
				{ indexed: false, internalType: 'uint256', name: 'collateralAmount', type: 'uint256' },
				{ indexed: false, internalType: 'uint256', name: 'collateralAfter', type: 'uint256' },
			],
			name: 'CollateralDeposited',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'address', name: 'account', type: 'address' },
				{ indexed: false, internalType: 'uint256', name: 'loanID', type: 'uint256' },
				{ indexed: false, internalType: 'uint256', name: 'amountWithdrawn', type: 'uint256' },
				{ indexed: false, internalType: 'uint256', name: 'collateralAfter', type: 'uint256' },
			],
			name: 'CollateralWithdrawn',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, internalType: 'uint256', name: 'ratio', type: 'uint256' }],
			name: 'CollateralizationRatioUpdated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, internalType: 'uint256', name: 'interestRate', type: 'uint256' }],
			name: 'InterestRateUpdated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, internalType: 'uint256', name: 'issueFeeRate', type: 'uint256' }],
			name: 'IssueFeeRateUpdated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, internalType: 'uint256', name: 'issueLimit', type: 'uint256' }],
			name: 'IssueLimitUpdated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, internalType: 'uint256', name: 'ratio', type: 'uint256' }],
			name: 'LiquidationRatioUpdated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'address', name: 'account', type: 'address' },
				{ indexed: false, internalType: 'uint256', name: 'loanID', type: 'uint256' },
				{ indexed: false, internalType: 'uint256', name: 'feesPaid', type: 'uint256' },
			],
			name: 'LoanClosed',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'address', name: 'account', type: 'address' },
				{ indexed: false, internalType: 'uint256', name: 'loanID', type: 'uint256' },
				{ indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
			],
			name: 'LoanCreated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'address', name: 'account', type: 'address' },
				{ indexed: false, internalType: 'uint256', name: 'loanID', type: 'uint256' },
				{ indexed: false, internalType: 'address', name: 'liquidator', type: 'address' },
			],
			name: 'LoanLiquidated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, internalType: 'bool', name: 'loanLiquidationOpen', type: 'bool' }],
			name: 'LoanLiquidationOpenUpdated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'address', name: 'account', type: 'address' },
				{ indexed: false, internalType: 'uint256', name: 'loanID', type: 'uint256' },
				{ indexed: false, internalType: 'address', name: 'liquidator', type: 'address' },
				{ indexed: false, internalType: 'uint256', name: 'liquidatedAmount', type: 'uint256' },
				{
					indexed: false,
					internalType: 'uint256',
					name: 'liquidatedCollateral',
					type: 'uint256',
				},
			],
			name: 'LoanPartiallyLiquidated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'address', name: 'account', type: 'address' },
				{ indexed: false, internalType: 'uint256', name: 'loanID', type: 'uint256' },
				{ indexed: false, internalType: 'uint256', name: 'repaidAmount', type: 'uint256' },
				{ indexed: false, internalType: 'uint256', name: 'newLoanAmount', type: 'uint256' },
			],
			name: 'LoanRepaid',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: false,
					internalType: 'uint256',
					name: 'minLoanCollateralSize',
					type: 'uint256',
				},
			],
			name: 'MinLoanCollateralSizeUpdated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: false, internalType: 'address', name: 'oldOwner', type: 'address' },
				{ indexed: false, internalType: 'address', name: 'newOwner', type: 'address' },
			],
			name: 'OwnerChanged',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, internalType: 'address', name: 'newOwner', type: 'address' }],
			name: 'OwnerNominated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, internalType: 'bool', name: 'isPaused', type: 'bool' }],
			name: 'PauseChanged',
			type: 'event',
		},
		{
			constant: true,
			inputs: [],
			name: 'COLLATERAL',
			outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'MAX_ADDRESSES_FROM_RESOLVER',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [],
			name: 'acceptOwnership',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'accountLoanLimit',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'address', name: '', type: 'address' }],
			name: 'accountOpenLoanCounter',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'address', name: '', type: 'address' },
				{ internalType: 'uint256', name: '', type: 'uint256' },
			],
			name: 'accountsSynthLoans',
			outputs: [
				{ internalType: 'address payable', name: 'account', type: 'address' },
				{ internalType: 'uint256', name: 'collateralAmount', type: 'uint256' },
				{ internalType: 'uint256', name: 'loanAmount', type: 'uint256' },
				{ internalType: 'uint256', name: 'mintingFee', type: 'uint256' },
				{ internalType: 'uint256', name: 'timeCreated', type: 'uint256' },
				{ internalType: 'uint256', name: 'loanID', type: 'uint256' },
				{ internalType: 'uint256', name: 'timeClosed', type: 'uint256' },
				{ internalType: 'uint256', name: 'loanInterestRate', type: 'uint256' },
				{ internalType: 'uint256', name: 'accruedInterest', type: 'uint256' },
				{ internalType: 'uint40', name: 'lastInterestAccrued', type: 'uint40' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'uint256', name: '_loanAmount', type: 'uint256' },
				{ internalType: 'uint256', name: '_seconds', type: 'uint256' },
			],
			name: 'accruedInterestOnLoan',
			outputs: [{ internalType: 'uint256', name: 'interestAmount', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'uint256', name: 'debtBalance', type: 'uint256' },
				{ internalType: 'uint256', name: 'collateral', type: 'uint256' },
			],
			name: 'calculateAmountToLiquidate',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'uint256', name: 'loanID', type: 'uint256' }],
			name: 'closeLoan',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'uint256', name: 'loanAmount', type: 'uint256' }],
			name: 'collateralAmountForLoan',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'collateralizationRatio',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'address', name: '_account', type: 'address' },
				{ internalType: 'uint256', name: '_loanID', type: 'uint256' },
			],
			name: 'currentInterestOnLoan',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'account', type: 'address' },
				{ internalType: 'uint256', name: 'loanID', type: 'uint256' },
			],
			name: 'depositCollateral',
			outputs: [],
			payable: true,
			stateMutability: 'payable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'getContractInfo',
			outputs: [
				{ internalType: 'uint256', name: '_collateralizationRatio', type: 'uint256' },
				{ internalType: 'uint256', name: '_issuanceRatio', type: 'uint256' },
				{ internalType: 'uint256', name: '_interestRate', type: 'uint256' },
				{ internalType: 'uint256', name: '_interestPerSecond', type: 'uint256' },
				{ internalType: 'uint256', name: '_issueFeeRate', type: 'uint256' },
				{ internalType: 'uint256', name: '_issueLimit', type: 'uint256' },
				{ internalType: 'uint256', name: '_minLoanCollateralSize', type: 'uint256' },
				{ internalType: 'uint256', name: '_totalIssuedSynths', type: 'uint256' },
				{ internalType: 'uint256', name: '_totalLoansCreated', type: 'uint256' },
				{ internalType: 'uint256', name: '_totalOpenLoanCount', type: 'uint256' },
				{ internalType: 'uint256', name: '_ethBalance', type: 'uint256' },
				{ internalType: 'uint256', name: '_liquidationDeadline', type: 'uint256' },
				{ internalType: 'bool', name: '_loanLiquidationOpen', type: 'bool' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'address', name: '_account', type: 'address' },
				{ internalType: 'uint256', name: '_loanID', type: 'uint256' },
			],
			name: 'getLoan',
			outputs: [
				{ internalType: 'address', name: 'account', type: 'address' },
				{ internalType: 'uint256', name: 'collateralAmount', type: 'uint256' },
				{ internalType: 'uint256', name: 'loanAmount', type: 'uint256' },
				{ internalType: 'uint256', name: 'timeCreated', type: 'uint256' },
				{ internalType: 'uint256', name: 'loanID', type: 'uint256' },
				{ internalType: 'uint256', name: 'timeClosed', type: 'uint256' },
				{ internalType: 'uint256', name: 'accruedInterest', type: 'uint256' },
				{ internalType: 'uint256', name: 'totalInterest', type: 'uint256' },
				{ internalType: 'uint256', name: 'totalFees', type: 'uint256' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'address', name: '_account', type: 'address' },
				{ internalType: 'uint256', name: '_loanID', type: 'uint256' },
			],
			name: 'getLoanCollateralRatio',
			outputs: [{ internalType: 'uint256', name: 'loanCollateralRatio', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'address', name: '_account', type: 'address' },
				{ internalType: 'uint256', name: '_loanID', type: 'uint256' },
			],
			name: 'getMintingFee',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'getResolverAddressesRequired',
			outputs: [{ internalType: 'bytes32[24]', name: 'addressesRequired', type: 'bytes32[24]' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'interestPerSecond',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'interestRate',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'contract AddressResolver', name: '_resolver', type: 'address' }],
			name: 'isResolverCached',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'issuanceRatio',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'issueFeeRate',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'issueLimit',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'lastPauseTime',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: '_loanCreatorsAddress', type: 'address' },
				{ internalType: 'uint256', name: '_loanID', type: 'uint256' },
				{ internalType: 'uint256', name: '_debtToCover', type: 'uint256' },
			],
			name: 'liquidateLoan',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: '_loanCreatorsAddress', type: 'address' },
				{ internalType: 'uint256', name: '_loanID', type: 'uint256' },
			],
			name: 'liquidateUnclosedLoan',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'liquidationDeadline',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'liquidationPenalty',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'liquidationRatio',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'uint256', name: 'collateralAmount', type: 'uint256' }],
			name: 'loanAmountFromCollateral',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'loanLiquidationOpen',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'minLoanCollateralSize',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
			name: 'nominateNewOwner',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'nominatedOwner',
			outputs: [{ internalType: 'address', name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'uint256', name: '_loanAmount', type: 'uint256' }],
			name: 'openLoan',
			outputs: [{ internalType: 'uint256', name: 'loanID', type: 'uint256' }],
			payable: true,
			stateMutability: 'payable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'address', name: '_account', type: 'address' }],
			name: 'openLoanIDsByAccount',
			outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'owner',
			outputs: [{ internalType: 'address', name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'paused',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: '_loanCreatorsAddress', type: 'address' },
				{ internalType: 'uint256', name: '_loanID', type: 'uint256' },
				{ internalType: 'uint256', name: '_repayAmount', type: 'uint256' },
			],
			name: 'repayLoan',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'resolver',
			outputs: [{ internalType: 'contract AddressResolver', name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			name: 'resolverAddressesRequired',
			outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'uint256', name: '_loanLimit', type: 'uint256' }],
			name: 'setAccountLoanLimit',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'uint256', name: 'ratio', type: 'uint256' }],
			name: 'setCollateralizationRatio',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'uint256', name: '_interestRate', type: 'uint256' }],
			name: 'setInterestRate',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'uint256', name: '_issueFeeRate', type: 'uint256' }],
			name: 'setIssueFeeRate',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'uint256', name: '_issueLimit', type: 'uint256' }],
			name: 'setIssueLimit',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'uint256', name: '_liquidationRatio', type: 'uint256' }],
			name: 'setLiquidationRatio',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'bool', name: '_loanLiquidationOpen', type: 'bool' }],
			name: 'setLoanLiquidationOpen',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'uint256', name: '_minLoanCollateralSize', type: 'uint256' }],
			name: 'setMinLoanCollateralSize',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'bool', name: '_paused', type: 'bool' }],
			name: 'setPaused',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'contract AddressResolver', name: '_resolver', type: 'address' }],
			name: 'setResolverAndSyncCache',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'address', name: '_account', type: 'address' },
				{ internalType: 'uint256', name: '_loanID', type: 'uint256' },
			],
			name: 'timeSinceInterestAccrualOnLoan',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'address', name: '_account', type: 'address' },
				{ internalType: 'uint256', name: '_loanID', type: 'uint256' },
			],
			name: 'totalFeesOnLoan',
			outputs: [
				{ internalType: 'uint256', name: 'interestAmount', type: 'uint256' },
				{ internalType: 'uint256', name: 'mintingFee', type: 'uint256' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'totalIssuedSynths',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'totalLoansCreated',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'totalOpenLoanCount',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'uint256', name: 'loanID', type: 'uint256' },
				{ internalType: 'uint256', name: 'withdrawAmount', type: 'uint256' },
			],
			name: 'withdrawCollateral',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
	],
};
