export default [
  'sUSD',
  'sAUD',
  'sEUR',
  'sJPY',
  'sKRW',
  'sGBP',
  'sCHF',
  'sBRL',
  'sCAD',
  'sINR',
  'sNZD',
  'sPLN',
  'sRUB',
  'sSGD',
  'sXAU',
  'sXAG',
  'sBTC',
];

export const SYNTH_SIGNS = {
  sUSD: '$',
  sAUD: '$',
  sEUR: '€',
  sJPY: '¥',
  sKRW: '₩',
  sGBP: '£',
  sCHF: 'Fr',
  sBRL: 'R$',
  sCAD: '$',
  sINR: '₹',
  sNZD: '$',
  sPLN: 'zł',
  sRUB: '₽',
  sSGD: '$',
  sXAU: 'oz',
  sXAG: 'oz',
  sBTC: '₿',
};

export const SYNTH_TYPES = {
  sUSD: 'currencies',
  sAUD: 'currencies',
  sEUR: 'currencies',
  sJPY: 'currencies',
  sKRW: 'currencies',
  sGBP: 'currencies',
  sCHF: 'currencies',
  sBRL: 'currencies',
  sCAD: 'currencies',
  sINR: 'currencies',
  sNZD: 'currencies',
  sPLN: 'currencies',
  sRUB: 'currencies',
  sSGD: 'currencies',
  sXAU: 'commodities',
  sXAG: 'commodities',
  sBTC: 'commodities',
};
