export default [
  'sBTC',
  'sXAU',
  'sXAG',
  'sUSD',
  'sAUD',
  'sEUR',
  'sJPY',
  'sKRW',
  'sGBP',
  'sCHF',
  'sBRL',
  'sCAD',
  'sINR',
  'sNZD',
  'sPLN',
  'sRUB',
  'sSGD',
];

export const SYNTH_SIGNS = {
  sUSD: '$',
  sAUD: '$',
  sEUR: '€',
  sJPY: '¥',
  sKRW: '₩',
  sGBP: '£',
  sCHF: 'Fr',
  sBRL: 'R$',
  sCAD: '$',
  sINR: '₹',
  sNZD: '$',
  sPLN: 'zł',
  sRUB: '₽',
  sSGD: '$',
  sXAU: 'oz',
  sXAG: 'oz',
  sBTC: '₿',
};

export const SYNTH_BY_TYPE = {
  sUSD: 'currencies',
  sAUD: 'currencies',
  sEUR: 'currencies',
  sJPY: 'currencies',
  sKRW: 'currencies',
  sGBP: 'currencies',
  sCHF: 'currencies',
  sBRL: 'currencies',
  sCAD: 'currencies',
  sINR: 'currencies',
  sNZD: 'currencies',
  sPLN: 'currencies',
  sRUB: 'currencies',
  sSGD: 'currencies',
  sXAU: 'commodities',
  sXAG: 'commodities',
  sBTC: 'crypto',
};

export const SYNTH_TYPES = ['currencies', 'commodities', 'crypto', 'stocks'];

export const CURRENCY_TABLE = {
  sUSD: 'USD',
  sEUR: 'EUR',
  sAUD: 'AUD',
  sJPY: 'JPY',
  sKRW: 'KRW',
  sGBP: 'GBP',
  sCHF: 'CHF',
  sBRL: 'BRL',
  sCAD: 'CAD',
  sINR: 'INR',
  sNZD: 'NZD',
  sPLN: 'PLN',
  sRUB: 'RUB',
  sSGD: 'SGD',
  sXAU: 'XAU',
  sXAG: 'XAG',
  sBTC: 'BTC',
};
